// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackMetal.API.Data;

#nullable disable

namespace TrackMetal.API.Migrations
{
    [DbContext(typeof(TrackMetalDbContext))]
    [Migration("20260109160721_CompletedConfigurations")]
    partial class CompletedConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackMetal.API.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.CommunityComments", b =>
                {
                    b.Property<int>("CommunityCommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityCommentsId"));

                    b.Property<int>("CommunityPostId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommunityCommentsId");

                    b.HasIndex("CommunityPostId");

                    b.ToTable("CommunityComments", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.CommunityPost", b =>
                {
                    b.Property<int>("CommunityPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityPostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommunityPostId");

                    b.ToTable("CommunityPosts", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.Corner", b =>
                {
                    b.Property<int>("CornerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CornerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CornerId");

                    b.HasIndex("TrackId");

                    b.ToTable("Corners", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.LapTime", b =>
                {
                    b.Property<int>("LapTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LapTimeId"));

                    b.Property<int>("LapTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sector1TimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sector2TimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sector3TimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LapTimeId");

                    b.HasIndex("TrackId");

                    b.ToTable("LapTimes", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.Setup", b =>
                {
                    b.Property<int>("SetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetupId"));

                    b.Property<string>("Aero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<double>("FuelLoad")
                        .HasColumnType("float");

                    b.Property<int>("Suspension")
                        .HasColumnType("int");

                    b.Property<int>("TireId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("SetupId");

                    b.HasIndex("CarId");

                    b.HasIndex("TrackId");

                    b.ToTable("Setups", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("CircuitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LapRecord")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceRating")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SafetyRating")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TrackMetal.API.Models.CommunityComments", b =>
                {
                    b.HasOne("TrackMetal.API.Models.CommunityPost", "CommunityPost")
                        .WithMany("Comments")
                        .HasForeignKey("CommunityPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Post_Comment");

                    b.Navigation("CommunityPost");
                });

            modelBuilder.Entity("TrackMetal.API.Models.Corner", b =>
                {
                    b.HasOne("TrackMetal.API.Models.Track", "Track")
                        .WithMany("Corners")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Track_Corner");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TrackMetal.API.Models.LapTime", b =>
                {
                    b.HasOne("TrackMetal.API.Models.Track", "Track")
                        .WithMany("LapTimes")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Track_LapTime");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TrackMetal.API.Models.Setup", b =>
                {
                    b.HasOne("TrackMetal.API.Models.Car", "Car")
                        .WithMany("Setups")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Car_Setup");

                    b.HasOne("TrackMetal.API.Models.Track", "Track")
                        .WithMany("Setups")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Track_Setup");

                    b.Navigation("Car");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TrackMetal.API.Models.Car", b =>
                {
                    b.Navigation("Setups");
                });

            modelBuilder.Entity("TrackMetal.API.Models.CommunityPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TrackMetal.API.Models.Track", b =>
                {
                    b.Navigation("Corners");

                    b.Navigation("LapTimes");

                    b.Navigation("Setups");
                });
#pragma warning restore 612, 618
        }
    }
}
